export const MOCK_VENDORS = [
  {
    id: 'v001',
    name: "Malee's Thai Kitchen",
    stall_number: 'A1',
    is_halal_certified: true,
    open_time: '08:00',
    close_time: '20:00',
    is_open: true,
    bio: 'Authentic Thai home cooking since 2015. Our recipes are passed down from generations of Thai grandmothers. Every dish is made to order with fresh herbs from our rooftop garden.',
    cuisine_tags: ['Thai', 'Rice Dishes', 'Curry'],
    estimated_wait_min: 5,
    cover_image_url: null,
    current_queue_count: 2,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'v002',
    name: 'Som Tam Station',
    stall_number: 'B3',
    is_halal_certified: false,
    open_time: '10:00',
    close_time: '19:00',
    is_open: true,
    bio: 'Isaan-style street food — fiery papaya salads, grilled chicken, and sticky rice straight from northeast Thailand.',
    cuisine_tags: ['Isaan', 'Grilled', 'Salads'],
    estimated_wait_min: 8,
    cover_image_url: null,
    current_queue_count: 7,
    created_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 'v003',
    name: 'Mama Noodle House',
    stall_number: 'C2',
    is_halal_certified: true,
    open_time: '07:30',
    close_time: '15:00',
    is_open: true,
    bio: 'Fresh hand-pulled noodles and soups. Our tom yum broth simmers for 8 hours every morning before the stall opens.',
    cuisine_tags: ['Noodles', 'Soup', 'Chinese-Thai'],
    estimated_wait_min: 12,
    cover_image_url: null,
    current_queue_count: 11,
    created_at: '2024-01-03T00:00:00Z',
  },
  {
    id: 'v004',
    name: 'Green Harvest',
    stall_number: 'D1',
    is_halal_certified: false,
    open_time: '08:00',
    close_time: '18:00',
    is_open: true,
    bio: '100% plant-based bowls, smoothies, and wraps. Organic ingredients sourced from local farmers every morning.',
    cuisine_tags: ['Vegetarian', 'Vegan', 'Healthy'],
    estimated_wait_min: 4,
    cover_image_url: null,
    current_queue_count: 1,
    created_at: '2024-01-04T00:00:00Z',
  },
];

export const MOCK_MENU_ITEMS = [
  // Malee's Thai Kitchen — v001
  {
    id: 'm001',
    vendor_id: 'v001',
    name: 'Pad Thai',
    description: 'Stir-fried rice noodles with egg, tofu, bean sprouts, and crushed peanuts in a classic tamarind sauce. A Bangkok street-food staple.',
    price: 55,
    category: 'Noodles',
    spice_level: 1,
    is_available: true,
    is_halal: true,
    is_vegetarian: false,
    is_jay: false,
    allergens: ['peanuts', 'eggs', 'shellfish'],
    tags: ['popular', 'noodles', 'street food'],
    ingredients: ['rice noodles', 'egg', 'tofu', 'bean sprouts', 'peanuts', 'tamarind sauce', 'fish sauce'],
    calories: 420,
    preparation_time_min: 8,
    image_url: null,
    is_featured: true,
    available_time_segment: 'all',
    release_date: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm002',
    vendor_id: 'v001',
    name: 'Green Curry with Rice',
    description: 'Creamy coconut green curry with Thai eggplant, basil leaves, and jasmine rice. Medium-hot and deeply aromatic.',
    price: 65,
    category: 'Curry',
    spice_level: 3,
    is_available: true,
    is_halal: true,
    is_vegetarian: false,
    is_jay: false,
    allergens: ['shellfish'],
    tags: ['spicy', 'curry', 'thai'],
    ingredients: ['coconut milk', 'green curry paste', 'chicken', 'Thai eggplant', 'basil', 'jasmine rice'],
    calories: 560,
    preparation_time_min: 10,
    image_url: null,
    is_featured: false,
    available_time_segment: 'lunch',
    release_date: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm003',
    vendor_id: 'v001',
    name: 'Khao Man Gai',
    description: 'Tender poached chicken on fragrant ginger rice with sliced cucumber, light broth, and a savory dipping sauce.',
    price: 50,
    category: 'Rice Dishes',
    spice_level: 0,
    is_available: true,
    is_halal: true,
    is_vegetarian: false,
    is_jay: false,
    allergens: ['soy'],
    tags: ['mild', 'halal', 'popular'],
    ingredients: ['chicken', 'jasmine rice', 'ginger', 'garlic', 'cucumber', 'soy sauce'],
    calories: 480,
    preparation_time_min: 5,
    image_url: null,
    is_featured: false,
    available_time_segment: 'all',
    release_date: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'm010',
    vendor_id: 'v001',
    name: 'Thai Milk Tea',
    description: 'Rich Thai-style iced tea brewed from orange pekoe, sweetened with condensed milk and crushed ice.',
    price: 35,
    category: 'Drinks',
    spice_level: 0,
    is_available: true,
    is_halal: true,
    is_vegetarian: true,
    is_jay: false,
    allergens: ['dairy'],
    tags: ['drink', 'popular', 'cold'],
    ingredients: ['Thai tea leaves', 'condensed milk', 'evaporated milk', 'sugar', 'ice'],
    calories: 240,
    preparation_time_min: 3,
    image_url: null,
    is_featured: false,
    available_time_segment: 'all',
    release_date: '2024-06-01T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
  },
  // Som Tam Station — v002
  {
    id: 'm004',
    vendor_id: 'v002',
    name: 'Som Tam Thai',
    description: 'Classic green papaya salad with cherry tomatoes, green beans, peanuts, dried shrimp, and a fiery lime dressing.',
    price: 45,
    category: 'Salads',
    spice_level: 4,
    is_available: true,
    is_halal: false,
    is_vegetarian: false,
    is_jay: false,
    allergens: ['peanuts', 'shellfish'],
    tags: ['spicy', 'isaan', 'salad'],
    ingredients: ['green papaya', 'tomatoes', 'green beans', 'peanuts', 'dried shrimp', 'fish sauce', 'lime', 'chili'],
    calories: 180,
    preparation_time_min: 6,
    image_url: null,
    is_featured: false,
    available_time_segment: 'lunch',
    release_date: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 'm005',
    vendor_id: 'v002',
    name: 'Gai Yang Set',
    description: 'Marinated charcoal-grilled chicken with sticky rice and spicy nam jim jeaw dipping sauce.',
    price: 70,
    category: 'Grilled',
    spice_level: 2,
    is_available: true,
    is_halal: false,
    is_vegetarian: false,
    is_jay: false,
    allergens: [],
    tags: ['grilled', 'isaan', 'hearty'],
    ingredients: ['chicken', 'lemongrass', 'garlic', 'turmeric', 'sticky rice', 'fish sauce'],
    calories: 620,
    preparation_time_min: 15,
    image_url: null,
    is_featured: false,
    available_time_segment: 'lunch',
    release_date: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
  },
  // Mama Noodle House — v003
  {
    id: 'm006',
    vendor_id: 'v003',
    name: 'Tom Yum Noodles',
    description: 'Spicy lemongrass broth with rice noodles, mushrooms, shrimp, and fresh herbs. Our signature bowl.',
    price: 60,
    category: 'Soup',
    spice_level: 3,
    is_available: true,
    is_halal: true,
    is_vegetarian: false,
    is_jay: false,
    allergens: ['shellfish'],
    tags: ['spicy', 'soup', 'noodles', 'popular'],
    ingredients: ['rice noodles', 'shrimp', 'mushrooms', 'lemongrass', 'galangal', 'kaffir lime leaves', 'chili', 'fish sauce'],
    calories: 340,
    preparation_time_min: 7,
    image_url: null,
    is_featured: false,
    available_time_segment: 'all',
    release_date: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
  },
  {
    id: 'm007',
    vendor_id: 'v003',
    name: 'Wonton Noodle Soup',
    description: 'Clear pork broth with handmade wontons, springy egg noodles, and fresh bok choy.',
    price: 55,
    category: 'Soup',
    spice_level: 0,
    is_available: true,
    is_halal: false,
    is_vegetarian: false,
    is_jay: false,
    allergens: ['gluten', 'eggs'],
    tags: ['mild', 'soup', 'noodles'],
    ingredients: ['egg noodles', 'pork wonton', 'bok choy', 'pork broth', 'garlic', 'soy sauce'],
    calories: 380,
    preparation_time_min: 8,
    image_url: null,
    is_featured: false,
    available_time_segment: 'breakfast',
    release_date: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
  },
  // Green Harvest — v004
  {
    id: 'm008',
    vendor_id: 'v004',
    name: 'Buddha Bowl',
    description: 'Quinoa base with roasted sweet potato, broccoli, avocado, chickpeas, and creamy tahini dressing.',
    price: 85,
    category: 'Bowls',
    spice_level: 0,
    is_available: true,
    is_halal: false,
    is_vegetarian: true,
    is_jay: true,
    allergens: ['sesame'],
    tags: ['vegan', 'healthy', 'bowls'],
    ingredients: ['quinoa', 'broccoli', 'sweet potato', 'avocado', 'chickpeas', 'tahini', 'lemon'],
    calories: 490,
    preparation_time_min: 10,
    image_url: null,
    is_featured: false,
    available_time_segment: 'all',
    release_date: '2024-01-04T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
  },
  {
    id: 'm009',
    vendor_id: 'v004',
    name: 'Tropical Smoothie',
    description: 'Mango, pineapple, and banana blended fresh with coconut milk. No added sugar.',
    price: 40,
    category: 'Drinks',
    spice_level: 0,
    is_available: true,
    is_halal: false,
    is_vegetarian: true,
    is_jay: true,
    allergens: [],
    tags: ['vegan', 'drink', 'healthy'],
    ingredients: ['mango', 'pineapple', 'banana', 'coconut milk'],
    calories: 220,
    preparation_time_min: 3,
    image_url: null,
    is_featured: false,
    available_time_segment: 'all',
    release_date: '2024-01-04T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
  },
];

// ─── Orders ───────────────────────────────────────────────────────────────────

export const MOCK_ORDERS = [
  {
    id: 'o000',
    vendor_id: 'v002',
    queue_number: 15,
    status: 'pending' as const,
    subtotal: 45,
    packaging_fee: 5,
    total_amount: 50,
    payment_method: 'wallet',
    pickup_start: '12:45',
    pickup_end: '13:00',
    time_segment: 'lunch',
    created_at: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    items: [{ name: 'Som Tam Thai', quantity: 1, unit_price: 45 }],
  },
  {
    id: 'o001',
    vendor_id: 'v003',
    queue_number: 7,
    status: 'ready' as const,
    subtotal: 60,
    packaging_fee: 5,
    total_amount: 65,
    payment_method: 'wallet',
    pickup_start: '12:15',
    pickup_end: '12:30',
    time_segment: 'lunch',
    created_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    items: [{ name: 'Tom Yum Noodles', quantity: 1, unit_price: 60 }],
  },
  {
    id: 'o002',
    vendor_id: 'v001',
    queue_number: 12,
    status: 'accepted' as const,
    subtotal: 145,
    packaging_fee: 5,
    total_amount: 150,
    payment_method: 'wallet',
    pickup_start: '12:30',
    pickup_end: '12:45',
    time_segment: 'lunch',
    created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    items: [
      { name: 'Pad Thai', quantity: 2, unit_price: 55 },
      { name: 'Thai Milk Tea', quantity: 1, unit_price: 35 },
    ],
  },
  {
    id: 'o003',
    vendor_id: 'v004',
    queue_number: 3,
    status: 'completed' as const,
    subtotal: 125,
    packaging_fee: 5,
    total_amount: 130,
    payment_method: 'wallet',
    pickup_start: '11:45',
    pickup_end: '12:00',
    time_segment: 'lunch',
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { name: 'Buddha Bowl', quantity: 1, unit_price: 85 },
      { name: 'Tropical Smoothie', quantity: 1, unit_price: 40 },
    ],
  },
  {
    id: 'o004',
    vendor_id: 'v001',
    queue_number: 8,
    status: 'completed' as const,
    subtotal: 65,
    packaging_fee: 5,
    total_amount: 70,
    payment_method: 'wallet',
    pickup_start: '13:00',
    pickup_end: '13:15',
    time_segment: 'lunch',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    items: [{ name: 'Green Curry with Rice', quantity: 1, unit_price: 65 }],
  },
  {
    id: 'o005',
    vendor_id: 'v002',
    queue_number: 5,
    status: 'cancelled' as const,
    subtotal: 115,
    packaging_fee: 5,
    total_amount: 120,
    payment_method: 'wallet',
    pickup_start: '12:00',
    pickup_end: '12:15',
    time_segment: 'lunch',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      { name: 'Som Tam Thai', quantity: 1, unit_price: 45 },
      { name: 'Gai Yang Set', quantity: 1, unit_price: 70 },
    ],
  },
];

// ─── Wallet ───────────────────────────────────────────────────────────────────

export const MOCK_WALLET_BALANCE = 480;

export const MOCK_WALLET_TRANSACTIONS = [
  {
    id: 'wt001',
    type: 'topup' as const,
    amount: 200,
    description: 'Top-up via PromptPay',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'wt002',
    type: 'payment' as const,
    amount: -150,
    description: "Malee's Thai Kitchen · #Q12",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 + 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'wt003',
    type: 'payment' as const,
    amount: -130,
    description: 'Green Harvest · #Q3',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'wt004',
    type: 'refund' as const,
    amount: 120,
    description: 'Refund — Som Tam Station order cancelled',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'wt005',
    type: 'payment' as const,
    amount: -70,
    description: "Malee's Thai Kitchen · #Q8",
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'wt006',
    type: 'topup' as const,
    amount: 500,
    description: 'Top-up via PromptPay',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

export function getVendorById(id: string) {
  return MOCK_VENDORS.find(v => v.id === id) ?? null;
}

export function getMenuItemById(id: string) {
  return MOCK_MENU_ITEMS.find(i => i.id === id) ?? null;
}

export function getMenuItemsByVendor(vendorId: string) {
  return MOCK_MENU_ITEMS.filter(i => i.vendor_id === vendorId);
}

export function getVendorName(vendorId: string) {
  return MOCK_VENDORS.find(v => v.id === vendorId)?.name ?? '';
}

export function getOrderById(id: string) {
  return MOCK_ORDERS.find(o => o.id === id) ?? null;
}
